### PR TITLE
Revised HW1_yb2334

### PR DESCRIPTION
**Pull request by waxla**
Revised after the class; Modified format, color, etc.

### CODE REVIEW

**Comment by waxla** [comment]
Seems submit the pull request to the new hw1 branch. Don't know if it's okay...

**Comment by malecki** [comment]
yes, that’s great! :cherry_blossom:

**Comment by ry2272** [comment]
Nice plots :)
Maybe you could order the x-bars in histogram to make it easier to see the trend.
Or maybe combine the six histograms into one and ordered them.
Add percentage value in the pie-chart

**Comment by ZhongjunHu** [comment]
Excellent!!

**Pull request merged**
