### PR TITLE
9-25-14-Michael-Pearlson-hw2

### PR DESCRIPTION
**Pull request by mapearlson**

### CODE REVIEW

**Comment by malecki** [comment]
can you `git mv` both these files to `hw2/_posts` so they will get linked
by the archive page?

**Comment by mapearlson** [comment]
I can't seem to get the new hw2/_posts folder into my local directory.  Can you suggest a way to do that?  When it fetch it does so, but then I attempt to merge and it says "merge upstream - not something we can merge."

**Comment by malecki** [comment]
`merge upstream/gh-pages` ?

**Comment by mapearlson** [comment]
well that brought everything from the remote, but now I've got a lot more issues.  I tried to move it, but I'm not sure what's happening.

**Comment by malecki** [comment]
ok. don't worry about it!

**Pull request merged**
