### PR TITLE
Hw1

### PR DESCRIPTION
**Pull request by liangquanzhou**
HW1
Learn to create a branch, commit, pull, push in github, and use Rmarkdown.to create html document.

### CODE REVIEW

**Comment by malecki** [comment]
could you please `git rm hw1/_posts/2014-09-18-HW1-Liangquan-Zhou_cache` (and commit and push)?

**Comment by liangquanzhou** [comment]
I think I commited and pushed it. I did it again. Is this one correct?

**Comment by malecki** [comment]
oops, my bad. It probably told you something like “not removing directory because you did not specify `-r`”

Please `git rm -rf hw1/_posts/2014-09-18-HW1-Liangquan-Zhou_cache` to remove that folder, commit&push. At the end you’ll see some number <28 at the top of here.
screen shot 2014-09-19 at 9 57 29 am

**Comment by liangquanzhou** [comment]
Can I do this at noon? I am already out of home for a class...

Thank you

**Comment by malecki** [comment]
absolutely, no rush. thanks!

**Comment by liangquanzhou** [comment]
I deleted the cache and now it's only 3 files changed.

**Comment by malecki** [comment]
many thanks! :grinning:

**Pull request merged**
