### PR TITLE
HW3...

### PR DESCRIPTION
**Pull request by benchowjm**
Not sure if this is the right thing to do but... here goes

### CODE REVIEW

**Comment by malecki** [comment]
hm, I see “hw1” in there. Can you commit hw3 files on your HW3 branch?

**Comment by benchowjm** [comment]
Hi,

I don't know what happened but my qmssviz folder on my desktop is now empty
with only the folders left. All my files have disappeared except for a
README. Is there a way to retrieve them back??

Ben

**Comment by malecki** [comment]
you around campus? stop by my office? or before/after class…

**Comment by benchowjm** [comment]
Sure I'll be down at about 1.30? I think I've managed to do it at last
though.

**Pull request closed without merging**
