### PR TITLE
2014-09-18-Jinho_Lee

### PR DESCRIPTION
**Pull request by jnonyx**
Jinho Lee's HW1

### CODE REVIEW

**Comment by lulutuan** [comment]
hellooooo

**Comment by jnonyx** [comment]
gmail treated it as a spam
hahahah!!!!

2014-09-17 21:53 GMT-04:00 lulutuan notifications@github.com:

**Comment by lulutuan** [comment]
Why did this to me!!

**Comment by malecki** [comment]
Please rename to follow the file naming convention, item 2 at https://github.com/malecki/qmssviz/blob/fc3e7eb151f7abc9b396b8c491bcf65fb5102b33/hw1/_posts/2014-09-11-assignment.Rmd

**Comment by jnonyx** [comment]
its not me
its gmail

2014-09-18 15:34 GMT-04:00 lulutuan notifications@github.com:

> Why did this to me!!
>

**Comment by malecki** [comment]
https://github.com/settings/notifications

**Comment by jnonyx** [comment]
I am sorry!
Meant to send it to my classmate about something else.

2014-09-18 15:48 GMT-04:00 Jinho Lee jnonyx@gmail.com:

**Pull request merged**
